storage: /verdaccio/storage

auth:
  gitlab:
    url: https://git.geektr.cloud
    publish: $maintainer
web:
  enable: true
  title: GeekTR.Cloud Node Package Manager
  logo: /-/static/logo.svg
  scope: \@geektr.cloud

uplinks:
  npmjs:
    url: http://registry.npm.taobao.org/
    cache: false

packages:
  '@geektr.cloud/*':
    access: $all
    publish: $authenticated
  '@private.geektr.cloud/*':
    access: $authenticated
    publish: $authenticated
  '**':
    access: $all
    publish: $authenticated
    proxy: npmjs

logs:
  - {type: stdout, format: pretty, level: http}
