version: '3'
services:
  verdaccio:
    container_name: verdaccio
    image: geektrcloud/verdaccio
    restart: unless-stopped
    volumes:
      - './logo.svg:/opt/verdaccio/node_modules/@verdaccio/ui-theme/static/logo.svg:ro'
      - './config.yaml:/verdaccio/conf/config.yaml:ro'
      - 'storage:/verdaccio/storage'

networks:
  default:
    external:
      name: '{{ docker_network_name }}'

volumes:
  storage:
    external:
      name: '{{ verdaccio.volumes.storage }}'
